import type {
  CollectiveEvent,
  Company,
  Inquiry,
  Insight,
  IntroductionItem,
  Member,
  Opportunity,
  Partner,
  PortalDocument,
  RegistrationItem,
  ResourceItem,
} from "@/lib/types";

export const demoCompanies: Company[] = [
  {
    id: "co-meridian",
    slug: "meridian-hold",
    name: "Meridian Hold",
    logoUrl: null,
    description:
      "A real-estate platform acquiring and operating multifamily and mixed-use assets across the Sun Belt. Meridian is built to hold, not flip.",
    industry: "Real estate",
    stage: "Operating",
    services: ["Acquisition", "Development", "Asset management"],
    website: "https://example.com/meridian",
    visibility: "public",
    status: "approved",
    featured: true,
    metrics: [
      { id: "m1", label: "Years operating", value: "11" },
      { id: "m2", label: "Properties", value: "18" },
      { id: "m3", label: "Markets", value: "4" },
    ],
    achievements: [
      {
        id: "a1",
        title: "Sun Belt assemblage",
        description: "Closed a four-parcel corridor without a public listing.",
        year: 2025,
      },
    ],
    people: [
      {
        slug: "keshan",
        name: "Keshan",
        role: "founder",
        title: "Principal",
        founder: true,
      },
      {
        slug: "chevy",
        name: "Chevy",
        role: "partner",
        title: "Technology and real estate",
        founder: false,
      },
    ],
    opportunities: [
      {
        slug: "operating-partner-east-corridor",
        title: "Operating partner for the East Corridor assemblage",
        type: "strategic_partner",
      },
    ],
  },
  {
    id: "co-alloy",
    slug: "alloy-circuit",
    name: "Alloy Circuit",
    logoUrl: null,
    description:
      "Applied technology for operators. Alloy builds internal systems for companies that own physical assets and regulated workflows.",
    industry: "Technology",
    stage: "Growth",
    services: ["Product", "Internal tools", "Data systems"],
    website: "https://example.com/alloy",
    visibility: "public",
    status: "approved",
    featured: true,
    metrics: [
      { id: "m4", label: "Projects", value: "30" },
      { id: "m5", label: "Ventures", value: "4" },
      { id: "m6", label: "Years operating", value: "6" },
    ],
    achievements: [
      {
        id: "a2",
        title: "Clinic operating system",
        description: "Replaced a patchwork of vendor tools across six locations.",
        year: 2026,
      },
    ],
    people: [
      {
        slug: "james",
        name: "James",
        role: "founder",
        title: "Founder",
        founder: true,
      },
      {
        slug: "chevy",
        name: "Chevy",
        role: "partner",
        title: "Technology and real estate",
        founder: false,
      },
    ],
    opportunities: [
      {
        slug: "growth-capital-alloy",
        title: "Growth capital for operator software",
        type: "capital",
      },
    ],
  },
  {
    id: "co-northline",
    slug: "northline-media",
    name: "Northline Media",
    logoUrl: null,
    description:
      "A media agency with an owned audience. Northline publishes, partners, and takes equity where distribution creates enterprise value.",
    industry: "Media agency",
    stage: "Operating",
    services: ["Publishing", "Partnerships", "Audience"],
    website: "https://example.com/northline",
    visibility: "public",
    status: "approved",
    featured: true,
    metrics: [
      { id: "m7", label: "Audience", value: "1.2M" },
      { id: "m8", label: "Years operating", value: "7" },
      { id: "m9", label: "Markets", value: "National" },
    ],
    achievements: [
      {
        id: "a3",
        title: "Equity partnership desk",
        description: "Shifted brand work from campaign fees to owned collaborations.",
        year: 2024,
      },
    ],
    people: [
      {
        slug: "julian",
        name: "Julian",
        role: "founder",
        title: "Principal",
        founder: true,
      },
    ],
    opportunities: [
      {
        slug: "cultural-series-partner",
        title: "Brand partner for a cultural series",
        type: "distribution",
      },
    ],
  },
  {
    id: "co-vesper",
    slug: "vesper-health",
    name: "Vesper Health",
    logoUrl: null,
    description:
      "Neighborhood clinics with payer relationships and an appetite for technology that respects clinical work.",
    industry: "Healthcare",
    stage: "Operating",
    services: ["Clinics", "Care delivery", "Partnerships"],
    website: "https://example.com/vesper",
    visibility: "public",
    status: "approved",
    featured: false,
    metrics: [
      { id: "m10", label: "Locations", value: "6" },
      { id: "m11", label: "Employees", value: "140" },
      { id: "m12", label: "Years operating", value: "9" },
    ],
    achievements: [
      {
        id: "a4",
        title: "Multi-site care model",
        description: "Opened three locations with a shared clinical standard.",
        year: 2023,
      },
    ],
    people: [
      {
        slug: "selene-ward",
        name: "Selene Ward",
        role: "founder",
        title: "Chief Executive",
        founder: true,
      },
    ],
    opportunities: [
      {
        slug: "technical-advisor-vesper",
        title: "Technical advisor for clinical operations",
        type: "talent",
      },
    ],
  },
  {
    id: "co-kinfolk",
    slug: "kinfolk-distribution",
    name: "Kinfolk Distribution",
    logoUrl: null,
    description:
      "Retail doors, logistics, and a point of view about which brands deserve scale. Kinfolk distributes with discipline.",
    industry: "Distribution",
    stage: "Operating",
    services: ["Wholesale", "Logistics", "Brand placement"],
    website: "https://example.com/kinfolk",
    visibility: "public",
    status: "approved",
    featured: false,
    metrics: [
      { id: "m13", label: "Customers", value: "220" },
      { id: "m14", label: "Locations", value: "3" },
      { id: "m15", label: "Years operating", value: "8" },
    ],
    achievements: [
      {
        id: "a5",
        title: "Regional wholesale network",
        description: "Built a buyer network that reorders without a trade-show cycle.",
        year: 2025,
      },
    ],
    people: [
      {
        slug: "andre-paul",
        name: "Andre Paul",
        role: "founder",
        title: "Principal",
        founder: true,
      },
    ],
    opportunities: [
      {
        slug: "joint-venture-consumer",
        title: "Joint venture with a consumer brand",
        type: "joint_venture",
      },
    ],
  },
  {
    id: "co-brooks",
    slug: "brooks-lane",
    name: "Brooks Lane",
    logoUrl: null,
    description:
      "Counsel and venture architecture for owners who intend to keep what they build. The work is structure, not spectacle.",
    industry: "Professional services",
    stage: "Operating",
    services: ["Transactions", "Ownership design", "Ventures"],
    website: "https://example.com/brookslane",
    visibility: "public",
    status: "approved",
    featured: false,
    metrics: [
      { id: "m16", label: "Transactions", value: "60+" },
      { id: "m17", label: "Ventures", value: "12" },
      { id: "m18", label: "Years operating", value: "14" },
    ],
    achievements: [
      {
        id: "a6",
        title: "Holding company formations",
        description: "Designed ownership stacks for operators entering a second asset class.",
        year: 2026,
      },
    ],
    people: [
      {
        slug: "curt",
        name: "Curt",
        role: "founder",
        title: "Principal",
        founder: true,
      },
    ],
    opportunities: [],
  },
];

export const demoMembers: Member[] = [
  {
    id: "mb-chevy",
    slug: "chevy",
    fullName: "Chevy",
    title: "Technology and real estate",
    bio: "Chevy works across technology and real estate, connecting operating software with assets the collective intends to hold.",
    photoUrl: null,
    city: "Atlanta",
    expertise: ["Technology", "Real estate", "Operator systems"],
    industries: ["Technology", "Real estate"],
    iHave: "A working view of both the technology and the real estate inside the collective.",
    iNeed: "Partners who can build in one discipline and hold in the other.",
    socials: { linkedin: "https://www.linkedin.com" },
    featured: true,
    isPublic: true,
    membershipStatus: "approved",
    companies: [
      { slug: "alloy-circuit", name: "Alloy Circuit", role: "Technology and real estate" },
      { slug: "meridian-hold", name: "Meridian Hold", role: "Technology and real estate" },
    ],
  },
  {
    id: "mb-james",
    slug: "james",
    fullName: "James",
    title: "Founder, Alloy Circuit",
    bio: "James builds software for operators who own buildings, clinics, and supply chains. The work is quiet, specific, and meant to stay in production.",
    photoUrl: null,
    city: "Chicago",
    expertise: ["Product", "Operator software", "Systems"],
    industries: ["Technology"],
    iHave: "A team that ships internal tools for operators who have outgrown spreadsheets.",
    iNeed: "Distribution into companies that will use the product, not pilot it forever.",
    socials: { linkedin: "https://www.linkedin.com", x: "https://x.com" },
    featured: true,
    isPublic: true,
    membershipStatus: "approved",
    companies: [{ slug: "alloy-circuit", name: "Alloy Circuit", role: "Founder" }],
  },
  {
    id: "mb-keshan",
    slug: "keshan",
    fullName: "Keshan",
    title: "Principal, Meridian Hold",
    bio: "Keshan acquires and operates real estate with a hold mentality, looking for partners who can execute.",
    photoUrl: null,
    city: "Atlanta",
    expertise: ["Acquisitions", "Asset management", "Mixed-use"],
    industries: ["Real estate"],
    iHave: "Operating partners and on-the-ground capacity across four Sun Belt markets.",
    iNeed: "Institutional equity for a 240-unit assemblage already under control.",
    socials: { linkedin: "https://www.linkedin.com", website: "https://example.com/meridian" },
    featured: true,
    isPublic: true,
    membershipStatus: "approved",
    companies: [{ slug: "meridian-hold", name: "Meridian Hold", role: "Principal" }],
  },
  {
    id: "mb-julian",
    slug: "julian",
    fullName: "Julian",
    title: "Principal, Northline Media",
    bio: "Julian runs a media agency that treats audience as an asset, and would rather own a collaboration than rent a campaign.",
    photoUrl: null,
    city: "New York",
    expertise: ["Audience", "Partnerships", "Agency"],
    industries: ["Media agency"],
    iHave: "An owned audience and a partnership desk that can move culture with discipline.",
    iNeed: "Equity collaborations with portfolio companies that have something real to distribute.",
    socials: { instagram: "https://instagram.com", website: "https://example.com/northline" },
    featured: true,
    isPublic: true,
    membershipStatus: "approved",
    companies: [{ slug: "northline-media", name: "Northline Media", role: "Principal" }],
  },
  {
    id: "mb-malik",
    slug: "malik-adeyemi",
    fullName: "Malik Adeyemi",
    title: "Investor",
    bio: "Malik allocates patient capital alongside a small circle of family offices. He backs operators with a path to ownership, not a path to a slide.",
    photoUrl: null,
    city: "Houston",
    expertise: ["Capital", "Governance", "Partnerships"],
    industries: ["Investing", "Real estate", "Technology"],
    iHave: "Patient capital and a network of families who prefer durable assets.",
    iNeed: "Operators building companies and properties they intend to keep.",
    socials: { linkedin: "https://www.linkedin.com" },
    featured: false,
    isPublic: true,
    membershipStatus: "approved",
    companies: [],
  },
  {
    id: "mb-selene",
    slug: "selene-ward",
    fullName: "Selene Ward",
    title: "Chief Executive, Vesper Health",
    bio: "Selene leads a group of clinics that stayed independent. She is looking for technology partners who have sat inside a regulated business.",
    photoUrl: null,
    city: "Dallas",
    expertise: ["Care delivery", "Payer relationships", "Operations"],
    industries: ["Healthcare"],
    iHave: "Clinics, payer relationships, and a clinical team that knows its standard.",
    iNeed: "Technology partners who understand regulated care and will build beside the operators.",
    socials: { linkedin: "https://www.linkedin.com" },
    featured: false,
    isPublic: true,
    membershipStatus: "approved",
    companies: [{ slug: "vesper-health", name: "Vesper Health", role: "Chief Executive" }],
  },
  {
    id: "mb-andre",
    slug: "andre-paul",
    fullName: "Andre Paul",
    title: "Principal, Kinfolk Distribution",
    bio: "Andre places brands into rooms where they can reorder. He is selective about what moves through the network.",
    photoUrl: null,
    city: "Los Angeles",
    expertise: ["Wholesale", "Logistics", "Brand"],
    industries: ["Distribution", "Consumer"],
    iHave: "Retail doors, logistics, and buyers who trust the edit.",
    iNeed: "Brands ready for disciplined scale, and a joint venture rather than a one-season push.",
    socials: { website: "https://example.com/kinfolk" },
    featured: false,
    isPublic: true,
    membershipStatus: "approved",
    companies: [{ slug: "kinfolk-distribution", name: "Kinfolk Distribution", role: "Principal" }],
  },
  {
    id: "mb-curt",
    slug: "curt",
    fullName: "Curt",
    title: "Principal, Brooks Lane",
    bio: "Curt designs ownership and helps founders enter a second asset class without losing the company they already built.",
    photoUrl: null,
    city: "Washington",
    expertise: ["Transactions", "Governance", "Ventures"],
    industries: ["Professional services"],
    iHave: "Transaction experience and a practice built around clean ownership structures.",
    iNeed: "Founders who want the paperwork to match the ambition.",
    socials: { linkedin: "https://www.linkedin.com" },
    featured: true,
    isPublic: true,
    membershipStatus: "approved",
    companies: [{ slug: "brooks-lane", name: "Brooks Lane", role: "Principal" }],
  },
  {
    id: "mb-isaiah",
    slug: "isaiah-grant",
    fullName: "Isaiah Grant",
    title: "Host, The Capital Table",
    bio: "Isaiah convenes The Capital Table. The room is small, the guest list is argued over, and the point is a decision.",
    photoUrl: null,
    city: "Atlanta",
    expertise: ["Relationships", "Convening", "Capital"],
    industries: ["Investing", "Media"],
    iHave: "Rooms where principals actually decide.",
    iNeed: "Principals. Not spectators.",
    socials: { linkedin: "https://www.linkedin.com" },
    featured: false,
    isPublic: true,
    membershipStatus: "approved",
    companies: [],
  },
];

export const demoOpportunities: Opportunity[] = [
  {
    id: "op-1",
    slug: "operating-partner-east-corridor",
    title: "Operating partner for the East Corridor assemblage",
    summary: "Meridian controls the land. The seat is for an operator who can deliver the mixed-use program.",
    description:
      "Four parcels are under control. The collective is looking for a strategic operating partner with multifamily execution experience, not a broker introduction. Public visibility is intentional: the work should be findable by the right firm.",
    type: "strategic_partner",
    visibility: "public",
    status: "approved",
    location: "Atlanta",
    deadline: "2026-12-15",
    featured: true,
    company: { slug: "meridian-hold", name: "Meridian Hold" },
  },
  {
    id: "op-2",
    slug: "growth-capital-alloy",
    title: "Growth capital for operator software",
    summary: "Alloy is raising patient capital to deepen product inside healthcare and property companies.",
    description:
      "This round is for members who understand operators. The company is not running a public process. Introductions from the collective are preferred.",
    type: "capital",
    visibility: "members",
    status: "approved",
    location: "Chicago",
    deadline: null,
    featured: true,
    company: { slug: "alloy-circuit", name: "Alloy Circuit" },
  },
  {
    id: "op-3",
    slug: "cultural-series-partner",
    title: "Brand partner for a cultural series",
    summary: "Northline is opening one equity-minded partnership around a seasonal series.",
    description:
      "The series already has an audience. The partner should want distribution and ownership, not a logo placement. A public listing is how outside firms begin the conversation.",
    type: "distribution",
    visibility: "public",
    status: "approved",
    location: "New York",
    deadline: "2026-11-30",
    featured: true,
    company: { slug: "northline-media", name: "Northline Media" },
  },
  {
    id: "op-4",
    slug: "off-market-assemblage",
    title: "Off-market assemblage",
    summary: "A private real-estate opportunity shared only with company members and administrators.",
    description:
      "Details stay inside the company circle until a counterparty is chosen. This record exists so the board can hold private opportunities beside public ones.",
    type: "real_estate",
    visibility: "private",
    status: "approved",
    location: "Undisclosed",
    deadline: null,
    featured: false,
    company: { slug: "meridian-hold", name: "Meridian Hold" },
  },
  {
    id: "op-5",
    slug: "technical-advisor-vesper",
    title: "Technical advisor for clinical operations",
    summary: "Vesper wants an advisor who has shipped software inside a care setting.",
    description:
      "The engagement can become a venture. Members with operating experience in healthcare technology should express interest directly.",
    type: "talent",
    visibility: "members",
    status: "approved",
    location: "Dallas",
    deadline: null,
    featured: false,
    company: { slug: "vesper-health", name: "Vesper Health" },
  },
  {
    id: "op-6",
    slug: "joint-venture-consumer",
    title: "Joint venture with a consumer brand",
    summary: "Kinfolk will put distribution against equity with one brand this year.",
    description:
      "The brand should already have a point of view and repeat customers. Kinfolk supplies doors and logistics. Ownership is shared.",
    type: "joint_venture",
    visibility: "public",
    status: "approved",
    location: "Los Angeles",
    deadline: "2027-01-31",
    featured: false,
    company: { slug: "kinfolk-distribution", name: "Kinfolk Distribution" },
  },
];

export const demoEvents: CollectiveEvent[] = [
  {
    id: "ev-capital",
    slug: "the-capital-table-autumn",
    series: "The Capital Table",
    title: "Autumn Session",
    description:
      "A private dinner for principals allocating capital, operating companies, or holding real assets. Twenty-four seats. Attendance is approved. The evening is a working conversation, not a panel.",
    startsAt: "2026-11-12T23:30:00.000Z",
    endsAt: "2026-11-13T02:30:00.000Z",
    location: "Atlanta — address shared upon approval",
    capacity: 24,
    inviteOnly: true,
    requiresApproval: true,
    visibility: "public",
    status: "published",
    featured: true,
    sponsors: [{ id: "pt-halden", name: "Halden Family Office" }],
  },
  {
    id: "ev-owners",
    slug: "owners-working-session",
    series: null,
    title: "Owners' Working Session",
    description:
      "A members' working session on ownership structures across technology, real estate, and operating companies. Bring a live question.",
    startsAt: "2026-12-03T19:00:00.000Z",
    endsAt: "2026-12-03T22:00:00.000Z",
    location: "Chicago",
    capacity: 40,
    inviteOnly: false,
    requiresApproval: false,
    visibility: "members",
    status: "published",
    featured: false,
    sponsors: [],
  },
];

export const demoPartners: Partner[] = [
  {
    id: "pt-halden",
    name: "Halden Family Office",
    description: "Patient capital for operators who keep their companies.",
    website: "https://example.com/halden",
    tier: "Capital",
    featured: true,
  },
  {
    id: "pt-brooks",
    name: "Brooks Lane Counsel",
    description: "Ownership design and transactions for the collective.",
    website: "https://example.com/brookslane",
    tier: "Counsel",
    featured: true,
  },
  {
    id: "pt-mercer",
    name: "Mercer Street Private Wealth",
    description: "Balance-sheet partners for families inside the room.",
    website: "https://example.com/mercer",
    tier: "Wealth",
    featured: false,
  },
  {
    id: "pt-atlas",
    name: "Atlas Founders Circle",
    description: "A university circle that sends operators, not spectators.",
    website: "https://example.com/atlas",
    tier: "Talent",
    featured: false,
  },
];

export const demoInsights: Insight[] = [
  {
    id: "in-1",
    slug: "ownership-is-an-operating-system",
    title: "Ownership is an operating system",
    excerpt: "Equity, audience, and real assets only compound when the structure is as serious as the ambition.",
    body: "The collective is not a feed of introductions.\n\nOwnership is the operating system: who holds the equity, who holds the audience, who holds the land, and who can still make a decision after the first success.\n\nWe publish when a pattern is worth keeping. The rest of the work stays in the room.",
    publishedAt: "2026-09-02T14:00:00.000Z",
    featured: true,
    visibility: "public",
  },
  {
    id: "in-2",
    slug: "what-we-mean-by-a-room",
    title: "What we mean by a room",
    excerpt: "A room is a guest list with consequences. The Capital Table is the clearest expression of that idea.",
    body: "A room is not a networking hour.\n\nIt is a finite guest list, a reason for gathering, and enough trust that a person can say what they need. The Capital Table exists so capital, operators, and distribution sit at the same table before a process goes public.\n\nIf you are looking for a panel, this is the wrong house.",
    publishedAt: "2026-08-11T14:00:00.000Z",
    featured: false,
    visibility: "public",
  },
  {
    id: "in-3",
    slug: "distribution-before-decoration",
    title: "Distribution before decoration",
    excerpt: "Media, retail doors, and relationships are distribution. Design comes after the path to market is real.",
    body: "Companies in this collective are asked a plain question: who already trusts you with attention, inventory, or capital?\n\nDistribution is a asset. Decoration is what you add once the asset is real. Northline, Kinfolk, and the member directory exist so those paths can meet without a conference lanyard.",
    publishedAt: "2026-07-18T14:00:00.000Z",
    featured: false,
    visibility: "public",
  },
];

export const demoResources: ResourceItem[] = [
  {
    id: "rs-1",
    title: "How to write an opportunity",
    summary: "State what you have, what you need, and who should not apply.",
    url: null,
    category: "Practice",
  },
  {
    id: "rs-2",
    title: "Introduction standard",
    summary: "Ask before you introduce. Context is part of the courtesy.",
    url: null,
    category: "Practice",
  },
  {
    id: "rs-3",
    title: "The Capital Table brief",
    summary: "What the dinner is for, and what it will not become.",
    url: null,
    category: "Events",
  },
];

export const demoDocuments: PortalDocument[] = [
  {
    id: "doc-1",
    title: "Membership principles",
    description: "The short document new members receive after approval.",
    visibility: "members",
    filePath: "preview/membership-principles.pdf",
    createdAt: "2026-06-01T14:00:00.000Z",
  },
  {
    id: "doc-2",
    title: "East Corridor overview",
    description: "A private briefing for the Meridian assemblage.",
    visibility: "private",
    filePath: "preview/east-corridor.pdf",
    createdAt: "2026-09-12T14:00:00.000Z",
  },
];

export const demoIntroductions: IntroductionItem[] = [
  {
    id: "intro-1",
    subject: "Alloy and Vesper",
    message: "Selene, James builds operator software. Worth a direct conversation about the clinics.",
    status: "requested",
    direction: "received",
    counterpart: "Isaiah Grant",
    counterpartSlug: "isaiah-grant",
    createdAt: "2026-10-01T14:00:00.000Z",
  },
  {
    id: "intro-2",
    subject: "Distribution for a portfolio brand",
    message: "Andre, this brand is ready for doors rather than another launch.",
    status: "accepted",
    direction: "sent",
    counterpart: "Andre Paul",
    counterpartSlug: "andre-paul",
    createdAt: "2026-09-20T14:00:00.000Z",
  },
];

export const demoInquiries: Inquiry[] = [
  {
    id: "inq-1",
    name: "Helena Voss",
    email: "helena@example.com",
    organization: "Voss & Co.",
    interest: "Membership",
    message: "We operate a logistics company and would like to understand how the collective considers new members.",
    createdAt: "2026-10-04T14:00:00.000Z",
  },
];

export const demoPendingMember: Member = {
  id: "mb-jordan",
  slug: "jordan-hale",
  fullName: "Jordan Hale",
  title: "Founder, Hale Studio",
  bio: "Awaiting approval.",
  photoUrl: null,
  city: "Detroit",
  expertise: ["Brand"],
  industries: ["Media"],
  iHave: "A studio with retained clients.",
  iNeed: "A path into ownership conversations.",
  socials: {},
  featured: false,
  isPublic: false,
  membershipStatus: "pending",
  companies: [],
};

export const demoPendingRegistrations: RegistrationItem[] = [
  {
    id: "reg-1",
    status: "pending",
    guestName: "Helena Voss",
    guestEmail: "helena@example.com",
    guestCompany: "Voss & Co.",
    guestTitle: "Principal",
    referralSource: "Halden Family Office",
    eventTitle: "The Capital Table — Autumn Session",
    eventSlug: "the-capital-table-autumn",
  },
];

export const previewViewer = {
  id: "preview-admin",
  email: "preview@billionairebrunch.example",
  fullName: "Steward",
  slug: "preview-steward",
  role: "admin" as const,
  membershipStatus: "approved" as const,
  preview: true,
};
